<?php
/**
* @file
* A description of what your module does.
*/

use \Drupal\striper\Entity\StriperPlanEntity;
use \Drupal\Core\Access\AccessResult;

function striper_plans_load($id) {
    return StriperPlanEntity::load($id);
}

/**
 * Implements hook_uninstall().
 */
function striper_uninstall() {
    $role = \Drupal\user\Entity\Role::load('stripe_subscriber');
    $role->delete();
}

/**
 * Implements hook_theme().
 */
function striper_theme($existing, $type, $theme, $path) {
    return array(
        'striper_plan_format' => array(
            'variables' => array(
                'action'=> NULL,
                'anon_url' => NULL,
                'price' => NULL,
                'data' => NULL,
                'logged_in' => NULL,
                'plan_name' => NULL,
            ),
        ),
        'striper_subscriptions' => array(
            'variables' => array(
                'link' => NULL,
                'subscription' => NULL,
            )
        ),
    );
}
