<?php
/**
* @file
* A description of what your module does.
*/

use \Drupal\striper\Entity\StriperPlanEntity;

function striper_plans_load($id) {
    return StriperPlanEntity::load($id);
}

/**
 * Implements hook_uninstall().
 */
function striper_uninstall() {
    $role = \Drupal\user\Entity\Role::load('stripe_subscriber');
    $role->delete();
}

/**
 * Implements hook_field_widget_info_alter().
 *
 * Allows stripe_checkout widget to be applied to number fields.
 */
function striper_field_widget_info_alter(array &$info) {
    $info['number']['field_types'][] = 'striper_checkout';
}

/**
 * Implements hook_theme().
 */
function striper_theme($existing, $type, $theme, $path) {
    return array(
        'striper_checkout' => array(
            'variables' => array(
                'action'=> NULL,
                'anon_url' => NULL,
                'price' => NULL,
                'data' => NULL,
                'logged_in' => NULL,
                'plan_name' => NULL,
            ),
        ),
        'striper_subscriptions' => array(
            'variables' => array(
                'link' => NULL,
                'subscription' => NULL,
            )
        ),
    );
}

