striper.striper_plan.*:
  type: mapping
  label: "Plan"
  mapping:
    id:
      type: string
      label: 'Plan ID'
    uuid:
      type: string
      label: 'UUID'
    plan_name:
      type: string
      label: 'Plan Name'
    plan_price:
      type: float
      label: 'Price of Plan'
    plan_frequency:
      type: string
      label: 'Plan Frequency'
    plan_active:
      type: boolean
      label: 'Active'
    plan_source:
      type: string
      label: 'Plan Source'
    plan_description:
      type: string
      label: 'Description'