<?php
/**
 * Created by PhpStorm.
 * User: jason
 * Date: 3/8/17
 * Time: 9:47 PM
 */

namespace Drupal\striper\Plugin\Block;


use Drupal\block\BlockForm;
use Drupal\Core\Block\BlockBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Provides a 'Striper' Block.
 *
 * @Block(
 *   id = "striper_payment_block",
 *   admin_label = @Translation("Striper payment block"),
 * )
 */

class StriperPaymentBlock extends BlockForm {


    public function build() {
        return array(
            '#markup' => $this->t('Hello World'),
            '#attached' => array(
                'library' => array('striper/striper.stripejs'),
            )
        );
    }

    public function defaultConfiguration() {
        return array(
            'Striper Sign-up Block' => $this->t('Allow users to sign up for your service.'),
        );
    }

    public function blockForm($form, FormStateInterface $form_state) {
        $form['subscriptions'] = array(
            '#type' => 'submit',
            '#value' => $this->t('Sign-up Today'),
        );

        return parent::blockForm($form, $form_state);
    }

    public function submitForm(array &$form, FormStateInterface $form_state) {
        parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub

        return $form_state->setRedirectUrl(Url::fromRoute('striper.app.subscriptions.list'));
    }
}