<?php
/**
 * Created by PhpStorm.
 * User: jason
 * Date: 3/9/17
 * Time: 1:28 PM
 */

namespace Drupal\striper;


use Drupal\Core\Entity\EntityAccessControlHandler;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

class StriperAccessController extends EntityAccessControlHandler {
    public function checkAccess(EntityInterface $entity, $operation, AccountInterface $account) {
        // TODO: actually implement checks...
        return parent::checkAccess($entity, $operation, $account); // TODO: Change the autogenerated stub
    }
}