<?php
/**
 * Created by PhpStorm.
 * User: jason
 * Date: 3/8/17
 * Time: 8:48 PM
 */

namespace Drupal\striper;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class StriperSyncSettingsForm extends ConfigFormBase {
    protected function getEditableConfigNames() {
        // TODO: Implement getEditableConfigNames() method.
    }

    public function getFormId() {
        // TODO: Implement getFormId() method.
    }

    public function buildForm(array $form, FormStateInterface $form_state) {
        return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
    }

}